"""auth tokens for verification and password reset

Revision ID: 2cb9132a8a77
Revises: 12c4e360d7a7
Created: 2026-08-13 12:18:01.678352+00:00

Migrations are additive/non-destructive by default. If this one drops or
rewrites anything, say so explicitly here and flag it in review (Part II §3).

Breaking change: no
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import sqlalchemy as sa
revision: str = '2cb9132a8a77'
down_revision: str | None = '12c4e360d7a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scd_auth_token',
    sa.Column('pk_auth_token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_ip', sa.String(length=45), nullable=True),
    sa.Column('scd_active_flag', sa.Boolean(), nullable=False),
    sa.Column('scd_active_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scd_active_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scd_changed_by', sa.Integer(), nullable=True, comment='Acting user id. Deliberately not a live FK: staff records are immutable historical references (Part I §2.2).'),
    sa.ForeignKeyConstraint(['fk_user_id'], ['scd_user.pk_user_id'], name=op.f('fk_scd_auth_token_fk_user_id_scd_user')),
    sa.PrimaryKeyConstraint('pk_auth_token_id', name=op.f('pk_scd_auth_token'))
    )
    with op.batch_alter_table('scd_auth_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scd_auth_token_fk_user_id'), ['fk_user_id'], unique=False)
        batch_op.create_index('ix_scd_auth_token_lookup', ['token_hash', 'purpose', 'scd_active_flag'], unique=False)
        batch_op.create_index(batch_op.f('ix_scd_auth_token_scd_active_flag'), ['scd_active_flag'], unique=False)
        batch_op.create_index(batch_op.f('ix_scd_auth_token_scd_active_from'), ['scd_active_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_scd_auth_token_scd_active_to'), ['scd_active_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_scd_auth_token_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index('ix_scd_auth_token_user_purpose', ['fk_user_id', 'purpose'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scd_auth_token', schema=None) as batch_op:
        batch_op.drop_index('ix_scd_auth_token_user_purpose')
        batch_op.drop_index(batch_op.f('ix_scd_auth_token_token_hash'))
        batch_op.drop_index(batch_op.f('ix_scd_auth_token_scd_active_to'))
        batch_op.drop_index(batch_op.f('ix_scd_auth_token_scd_active_from'))
        batch_op.drop_index(batch_op.f('ix_scd_auth_token_scd_active_flag'))
        batch_op.drop_index('ix_scd_auth_token_lookup')
        batch_op.drop_index(batch_op.f('ix_scd_auth_token_fk_user_id'))

    op.drop_table('scd_auth_token')
    # ### end Alembic commands ###
