"""add product search text projection

Revision ID: 12c4e360d7a7
Revises: 82a285e326b5
Created: 2026-08-12 18:30:41.345957+00:00

Migrations are additive/non-destructive by default. If this one drops or
rewrites anything, say so explicitly here and flag it in review (Part II §3).

Breaking change: no
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '12c4e360d7a7'
down_revision: str | None = '82a285e326b5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scd_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_text_ar', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('search_text_en', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scd_product', schema=None) as batch_op:
        batch_op.drop_column('search_text_en')
        batch_op.drop_column('search_text_ar')

    # ### end Alembic commands ###
