"""variant display name

Adds a bilingual, optional display label to product variants. Until now a
variant was identifiable only by its SKU, so staff had no way to say "Black" or
"Large" and shoppers had nothing to choose between (Part I §1, §5.4).

Purely additive: both columns are nullable, so every existing variant stays
valid and unchanged.

Revision ID: 768bac19898b
Revises: 2cb9132a8a77
Created: 2026-08-15 10:04:51.539780+00:00

Migrations are additive/non-destructive by default. If this one drops or
rewrites anything, say so explicitly here and flag it in review (Part II §3).

Breaking change: no
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '768bac19898b'
down_revision: str | None = '2cb9132a8a77'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scd_product_variant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_ar', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('name_en', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scd_product_variant', schema=None) as batch_op:
        batch_op.drop_column('name_en')
        batch_op.drop_column('name_ar')

    # ### end Alembic commands ###
