"""product attribute values on variants

Custom product details (Part I §5.2) are defined once in
``lkp_product_attribute`` and given values in ``scd_product_attribute_value``.
Until now a value could only hang off a product, so an attribute whose answer
differs per variant — dimensions on a bracelet that comes in two sizes — had
nowhere to go.

This adds ``fk_product_variant_id``, scoped exactly the way a gallery image
already is (§5.4): null means the value is the product's and every variant
inherits it, set means it belongs to that one variant.

Purely additive. The column is nullable, so every existing row stays valid and
keeps its current meaning — a product-wide value.

Revision ID: 320102a347f4
Revises: 768bac19898b
Created: 2026-08-28 12:12:39.603112+00:00

Migrations are additive/non-destructive by default. If this one drops or
rewrites anything, say so explicitly here and flag it in review (Part II §3).

Breaking change: no
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '320102a347f4'
down_revision: str | None = '768bac19898b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scd_product_attribute_value', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_product_variant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_scd_product_attribute_value_fk_product_variant_id'), ['fk_product_variant_id'], unique=False)
        batch_op.create_index('ix_scd_product_attribute_value_scope', ['fk_product_id', 'fk_product_variant_id', 'scd_active_flag'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_scd_product_attribute_value_fk_product_variant_id_scd_product_variant'), 'scd_product_variant', ['fk_product_variant_id'], ['pk_product_variant_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scd_product_attribute_value', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_scd_product_attribute_value_fk_product_variant_id_scd_product_variant'), type_='foreignkey')
        batch_op.drop_index('ix_scd_product_attribute_value_scope')
        batch_op.drop_index(batch_op.f('ix_scd_product_attribute_value_fk_product_variant_id'))
        batch_op.drop_column('fk_product_variant_id')

    # ### end Alembic commands ###
