"""All ORM models.

Importing this package registers every table on ``Base.metadata`` — which is
what Alembic autogenerate reads, so a model that is not re-exported here would
silently never get a migration. Keep the lists below complete.
"""

from app.db.base import Base
from app.models.access import (
    ApprovalChecker,
    ApprovalDecision,
    ApprovalRequest,
    ApprovalRequestParameter,
    AuditLog,
    AuditLogField,
    LoginAsScope,
    Permission,
    PermissionGrant,
)
from app.models.activity import ActivityEventLog, LoginAttempt, UserSession
from app.models.catalog import (
    Category,
    Discount,
    Product,
    ProductAttribute,
    ProductAttributeChoice,
    ProductAttributeValue,
    ProductCategory,
    ProductImage,
    ProductReview,
    ProductTag,
    ProductVariant,
    ProductViewEvent,
    Publisher,
    Tag,
    UrlRedirect,
    VariantOption,
    VariantOptionChoice,
    VariantOptionValue,
)
from app.models.consignment import (
    Consignment,
    ConsignmentItem,
    ConsignmentSale,
    ConsignmentSettlement,
    Consignor,
)
from app.models.identity import (
    Address,
    AuthToken,
    CompanyContact,
    CompanyPhone,
    CompanyProfile,
    Country,
    IndividualProfile,
    Province,
    Role,
    User,
)
from app.models.inventory import (
    Branch,
    BranchHours,
    OperatingCost,
    Shipment,
    ShipmentLine,
    StockLevel,
    StockMovement,
    StockPool,
    StockTake,
    StockTakeLine,
    StockTransfer,
    StockTransferLine,
)
from app.models.marketing import (
    AnnouncementBar,
    EmailOutbox,
    EmailTemplate,
    HomepageSection,
    HomepageSectionItem,
    NewsletterSubscription,
    Promocode,
    PromocodeRedemption,
    PromocodeRestriction,
    SiteSetting,
)
from app.models.money import (
    ExchangeRate,
    MoneyAllocation,
    MoneyBox,
    MoneyBoxReconciliation,
    MoneyTransaction,
    StoreCreditEntry,
)
from app.models.orders import (
    Cart,
    CartLine,
    CompareEntry,
    Order,
    OrderLine,
    OrderReturn,
    OrderReturnLine,
    Payment,
    PaymentChannel,
    RecentlyViewed,
    ShippingRule,
    Wishlist,
)

__all__ = [
    "Base",
    # access
    "ApprovalChecker",
    "ApprovalDecision",
    "ApprovalRequest",
    "ApprovalRequestParameter",
    "AuditLog",
    "AuditLogField",
    "LoginAsScope",
    "Permission",
    "PermissionGrant",
    # activity
    "ActivityEventLog",
    "LoginAttempt",
    "UserSession",
    # catalog
    "Category",
    "Discount",
    "Product",
    "ProductAttribute",
    "ProductAttributeChoice",
    "ProductAttributeValue",
    "ProductCategory",
    "ProductImage",
    "ProductReview",
    "ProductTag",
    "ProductVariant",
    "ProductViewEvent",
    "Publisher",
    "Tag",
    "UrlRedirect",
    "VariantOption",
    "VariantOptionChoice",
    "VariantOptionValue",
    # consignment
    "Consignment",
    "ConsignmentItem",
    "ConsignmentSale",
    "ConsignmentSettlement",
    "Consignor",
    # identity
    "Address",
    "CompanyContact",
    "CompanyPhone",
    "CompanyProfile",
    "Country",
    "IndividualProfile",
    "AuthToken",
    "Province",
    "Role",
    "User",
    # inventory
    "Branch",
    "BranchHours",
    "OperatingCost",
    "Shipment",
    "ShipmentLine",
    "StockLevel",
    "StockMovement",
    "StockPool",
    "StockTake",
    "StockTakeLine",
    "StockTransfer",
    "StockTransferLine",
    # marketing
    "AnnouncementBar",
    "EmailOutbox",
    "EmailTemplate",
    "HomepageSection",
    "HomepageSectionItem",
    "NewsletterSubscription",
    "Promocode",
    "PromocodeRedemption",
    "PromocodeRestriction",
    "SiteSetting",
    # money
    "ExchangeRate",
    "MoneyAllocation",
    "MoneyBox",
    "MoneyBoxReconciliation",
    "MoneyTransaction",
    "StoreCreditEntry",
    # orders
    "Cart",
    "CartLine",
    "CompareEntry",
    "Order",
    "OrderLine",
    "OrderReturn",
    "OrderReturnLine",
    "Payment",
    "PaymentChannel",
    "RecentlyViewed",
    "ShippingRule",
    "Wishlist",
]
